replicaCount: 1

imagePullSecrets:
  - name: gitlab-registry

persistence:
  enabled: true

shared:
  uploadStorage:
    size: 10Gi
    className: nfs

podSecurityContext: &podSecValues
  runAsUser: 197
  runAsGroup: 55000
  fsGroup: 55000
  fsGroupChangePolicy: "OnRootMismatch"

worker:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      memory: "1Gi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  podSecurityContext: *podSecValues

ingress:
  enabled: true
  hosts:
    - host: staging-harvard-curiosity.notch8.cloud
      paths:
        - path: /
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/proxy-body-size: "0",
    cert-manager.io/cluster-issuer: "letsencrypt-prod",
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  }
  tls:
    - hosts:
        - staging-harvard-curiosity.notch8.cloud
      secretName: harvard-curiosity-tls

postgresql:
  enabled: false
  persistence:
    size: 100Gi
externalPostgresql:
  host: pg-postgresql.staging-postgres.svc.cluster.local
  username: postgres
  password: $STAGING_POSTGRES_PASSWORD
  database: staging-harvard-spotlight

fcrepo:
  resources:
    limits:
      memory: "4Gi"
      cpu: "2"
    requests:
      memory: "2Gi"
      cpu: "1"
  enabled: false
externalFcrepoHost: fcrepo.staging-fcrepo.svc.cluster.local

solr:
  enabled: false
externalSolrPassword: $SOLR_ADMIN_PASSWORD
externalSolrHost: solr.staging-solr.svc.cluster.local
externalSolrUser: admin
externalSolrCollection: "harvard-spotlight"

worker:
  enabled: true

env:
  configmap:
    APP_HOST: staging-harvard-curiosity.notch8.cloud
    AUTH_STRATEGY: login
    SENTRY_DSN: https://91c4c4f789f84344a9e7f6952e8e05cc@o1008683.ingest.sentry.io/6745031
