name: "Build Test Lint"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  # build:
  #   uses: scientist-softserv/actions/.github/workflows/build.yaml@main
  #   with:
  #     platforms: "linux/amd64"
  #     worker: false
  #     # tag: deca90d9
  test:
    # needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@v0.0.1
    with:
      worker: false
      tag: d8a3fdb5
  lint:
    # needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@v0.0.1
    with:
      worker: false
      tag: d8a3fdb5
  retag:
    # needs: build
    uses: scientist-softserv/actions/.github/workflows/retag.yaml@v0.0.1
    with:
      worker: false
