name: "Build Test Lint"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@v0.0.3
    if: github.repository == 'scientist-softserv/harvard-curiosity'
    with:
      platforms: "linux/amd64"
      worker: false
      # tag: deca90d9
  lint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@main
    if: github.repository == 'scientist-softserv/harvard-curiosity'
    with:
      worker: false
      # tag: deca90d9
