
name: Rails tests
on: [push]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
      - name: fix bundler
        run: gem install bundler:2.1.4
      - name: Bundle installer
        run: bundle install
      - name: Test Connection 3
        run: mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS test3;'
      - name: create db
        run: rails db:create
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          MYSQL_USER: root
          MYSQL_SOCKET: /tmp/mysql.sock
          RAILS_ENV: test
      - name: migrate db
        run: rails db:migrate
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          MYSQL_USER: root
          MYSQL_SOCKET: /tmp/mysql.sock
          RAILS_ENV: test
      - name: Run tests
        run: bundle exec rspec
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          MYSQL_USER: root
          MYSQL_SOCKET: /tmp/mysql.sock
          RAILS_ENV: test